###Create Category
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "language": "en",
    "name": "Yes sir",
    "author": "6113cee6f951fe3e4059c5da"
}

###Create Category
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "language": "en",
    "author": "6113cee6f951fe3e4059c5da",
    "set":
    [
        "6116846b13b64460047a8482"
    ]
}

### Add Set to Category
PATCH http://localhost:3000/api/category/6116c92520c4bf5834f0fef2/6116846b13b64460047a8413?option=addset

### Remove Set from Category
PATCH http://localhost:3000/api/category/6116c92520c4bf5834f0fef2/6116846b13b64460047a8413?option=removeset

### Update Category Metadata
PATCH http://localhost:3000/api/category/6116c92520c4bf5834f0fef2
Content-Type: application/json

{
    "language": "en",
    "name": "Big PP gayming"
}

### Get all Categories
GET http://localhost:3000/api/category

### Get one Category
GET http://localhost:3000/api/category/6116b7142de49944c4becb88

# ### Get top 10 Sets in this Category TODO!!!!
# GET http://localhost:3000/api/category

### Soft Delete Category by Id TODO!!!!
DELETE http://localhost:3000/api/category

### Hard Delete Category by Id (require admin role)
DELETE http://localhost:3000/api/category