###Create Category
POST http://localhost:3000/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "language": "en",
    "name": "Yes sir",
    "author": "6113cee6f951fe3e4059c5da"
}

###Create Category
POST http://localhost:3000/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "language": "en",
    "author": "6113cee6f951fe3e4059c5da",
    "set":
    [
        "6116846b13b64460047a8482"
    ]
}

### Add Set to Category
PATCH http://localhost:3000/api/category/61193ad639f43fa06428c886/add/61193ad639f43fa06428c886
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

### Remove Set from Category
PATCH http://localhost:3000/api/category/61193ad639f43fa06428c886/remove/61193ad639f43fa06428c886
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

### Update Category Metadata ---- set author and xx are supposed to be ignored!
PATCH http://localhost:3000/api/category/6116c92520c4bf5834f0fef2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "language": "en",
    "name": "Big PP gayming",
    "author": "6113cee6f951fe3e4059c5db",
    "set": ["6116846b13b64460047a8413","6116846b13b64460047a8412"],
    "xx": "xxx"
}

### Get all Categories
GET http://localhost:3000/api/category?page=0

### Get one Category
GET http://localhost:3000/api/category/611928abefb0f27a182977ce

### Get top 10 Sets in this Category
GET http://localhost:3000/api/category/6116c92520c4bf5834f0fef2/toptensets

### Get all Sets in this Category
GET http://localhost:3000/api/category/6116c92520c4bf5834f0fef2/sets

### Soft Delete Category by Id
DELETE http://localhost:3000/api/category/6119382bcd1c889aa0aa7c2c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

### Hard Delete Category by Id (require admin role)
DELETE http://localhost:3000/api/category/6119382bcd1c889aa0aa7c2c?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI
