###Create Task
POST http://localhost:3000/api/task
Content-Type: application/json

{
    "language": "de",
    "type": "dare",
    "content": 
    {
        "currentPlayerGender": "@ca",
        "message": "This is a valid question"
    }
}

### Update Task
PATCH http://localhost:3000/api/task
Content-Type: application/json

{
    // TODO
}

### Get all Tasks
GET http://localhost:3000/api/task