###Create Task
POST http://localhost:3000/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvcGVzaG90Iiwic3ViIjoiNjExOTYxYTgxZmEyOTkwMDE2MjM2YWFhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkyMzE4NTQsImV4cCI6MTYyOTI2Nzg1NH0.Bh_4A-rAWCxcTbOH7N3eUfvs-AtutlM3o50Jguy8xw8

{
    "language": "de",
    "type": "dare",
    "author": "611961a81fa2990016236aaa",
    "content": {
        "currentPlayerGender": "@ca",
        "message": "füttere die @a mit etwas Leckerem."
    }
}

###Create Task
POST http://localhost:3000/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "language": "de",
    "type": "dare",
    "author": "6113cee6f951fe3e4059c5da",
    "content": 
    {
        "currentPlayerGender": "@ca",
        "message": "Stick your ringfinger into @m's nose and then into @a's ear."
    }
}

### Update Task
PATCH http://localhost:3000/api/task/6117d43c51e15a81fc269715
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "language": "de",
    "type": "truth",
    "content": {
        "currentPlayerGender": "@cm",
        "message": "@m @m @m @m @a @a @a"
    }
}

### Update Task with upvote
PATCH http://localhost:3000/api/task/611c1e3b1c20a66b5cdad7c3/upvote

### Update Task with downpvote
PATCH http://localhost:3000/api/task/611c1e3b1c20a66b5cdad7c3/downvote

### Get all Tasks
GET http://localhost:3000/api/task

### Get one Task
GET http://localhost:3000/api/task/6114edf7b4bd8303888ec67d

### Get top 10 Task
GET http://localhost:3000/api/task/topten

### Soft Delete Task by Id
DELETE http://localhost:3000/api/task/6114edf7b4bd8303888ec67d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

### Hard Delete Task by Id (require admin role)
DELETE http://localhost:3000/api/task/6114edf7b4bd8303888ec67d?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI
