###Create Task
POST http://localhost:3000/api/task
Content-Type: application/json

{
    "language": "de",
    "type": "dare",
    "author": "6113cee6f951fe3e4059c5da",
    "content": 
    {
        "currentPlayerGender": "@ca",
        "message": "Grow a fullbeard!"
    }
}

###Create Task
POST http://localhost:3000/api/task
Content-Type: application/json

{
    "language": "de",
    "type": "dare",
    "author": "6113cee6f951fe3e4059c5da",
    "content": 
    {
        "currentPlayerGender": "@ca",
        "message": "Stick your ringfinger into @m's nose and then into @a's ear."
    }
}

### Update Task
PATCH http://localhost:3000/api/task/6114edf7b4bd8303888ec67d
Content-Type: application/json

{
    "language": "en",
    "type": "truth",
    "content": 
    {
        "currentPlayerGender": "@cm",
        "message": "@m @m @m @m @a @a @a"
    }
}

### Update Task with upvote
PATCH http://localhost:3000/api/task/6114edf7b4bd8303888ec67d/upvote

### Update Task with upvote
PATCH http://localhost:3000/api/task/6114edf7b4bd8303888ec67d/downvote

### Get all Tasks
GET http://localhost:3000/api/task

### Get one Task
GET http://localhost:3000/api/task/6114edf7b4bd8303888ec67d

### Get top 10 Task
GET http://localhost:3000/api/task/topten

### Soft Delete Task by Id
DELETE http://localhost:3000/api/task/6114edf7b4bd8303888ec67d

### Hard Delete Task by Id (require admin role)
DELETE http://localhost:3000/api/task/6114edf7b4bd8303888ec67d?type=hard