@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjFiZmIyNTEwZjkyZTUzMjc4ZmNmNjQ4Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NDAwMjA1ODUsImV4cCI6MTY0MDA1NjU4NX0.bxCjgtGHoeuNsaMgHPkD14TTElasmQTDHZh6TH4VC5o
@user = 6191152856c9af0c03b1fb6c
@adress = http://localhost:3000/api/user
### Get current User
GET {{adress}}/profile
Authorization: Bearer {{token}}

### Get all User (Protected Route for Testing Reasons, access only with admin role)
GET {{adress}}
Authorization: Bearer {{token}}

### Patch user by id 
PATCH {{adress}}/{{user}}
Content-Type: application/json

{
    "role": "d",
    "username": "Haha",
    "email": "45@email.com"
}

### Patch user by id 
PATCH {{adress}}/testing/{{user}}
Content-Type: application/json

{
    "role": "admin"
}

### Delete User
DELETE {{adress}}/{{user}}

### 
GET {{adress}}/verify/98e97d273c8345eac435edeeb15a143c248f529cb07df581730512da1f77b8662c50265967f66f7592ec905213f5ffbab37dbd7aa1c9c13fedde8372fd62106a

### Rerequest verify

GET {{adress}}/getVerify
Authorization: Bearer {{token}}

### ResetPassword
GET {{adress}}/password-reset
Content-Type: application/json

{
    "userMail": "test@test.de"
}

### Reset password (change code)
POST {{adress}}/password-reset/284a2a050082eac63e7e0617daf69d606e8200fce1a0dc6e817902f35ea2394e5f803fc66bf5440e5bd74c8c5bf3fed75099c13dc9eae0d2d835193ce801369e
Content-Type: application/json

{
    "password": "this password was updated"
}

###
POST {{adress}}/submitReset
Content-Type: application/json

{
    "password": "funky",
    "code":"fresh"
}
