### Get current User
GET http://localhost:3000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExNmFmMDhkYWIwNjEzNTc0MzVlMGU5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4ODc2NzgwLCJleHAiOjE2Mjg5MTI3ODB9.PCzWu_EDhEqAoP4T95RfQZWbudImpUWlS0wYZ7SHSlo

### Get all User (Protected Route for Testing Reasons, access only with admin role)
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExNmFmMDhkYWIwNjEzNTc0MzVlMGU5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4ODc2NzgwLCJleHAiOjE2Mjg5MTI3ODB9.PCzWu_EDhEqAoP4T95RfQZWbudImpUWlS0wYZ7SHSlo

### Patch user by id 
PATCH http://localhost:3000/api/user/6116b5a5c5eae23f344d2d23
Content-Type: application/json

{
    "role": "d",
    "username": "Haha",
    "email": "45@email.com"
}

### Delete User
DELETE http://localhost:3000/api/user/61152d6fb3dac55cbcd081f2

### 
GET http://localhost:3000/api/user/verify/92de543f356bd1bcfa57c7cdfd90bec7f3ee0d377064b762ef398ebcb4e4d629e23ffff00debb07a2fed6e5cc81672ce56aaa3c828926b5eca329db3da2ce7f6