### Get current User
GET http://localhost:3000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExNmFmMDhkYWIwNjEzNTc0MzVlMGU5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4ODc2NzgwLCJleHAiOjE2Mjg5MTI3ODB9.PCzWu_EDhEqAoP4T95RfQZWbudImpUWlS0wYZ7SHSlo

### Get all User (Protected Route for Testing Reasons, access only with admin role)
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExNmFmMDhkYWIwNjEzNTc0MzVlMGU5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4ODc2NzgwLCJleHAiOjE2Mjg5MTI3ODB9.PCzWu_EDhEqAoP4T95RfQZWbudImpUWlS0wYZ7SHSlo

### Patch user by id 
PATCH http://localhost:3000/api/user/6116b5a5c5eae23f344d2d23
Content-Type: application/json

{
    "role": "d",
    "username": "Haha",
    "email": "45@email.com"
}

### Delete User
DELETE http://localhost:3000/api/user/61152d6fb3dac55cbcd081f2

### 
GET http://localhost:3000/api/user/verify/98e97d273c8345eac435edeeb15a143c248f529cb07df581730512da1f77b8662c50265967f66f7592ec905213f5ffbab37dbd7aa1c9c13fedde8372fd62106a

### Rerequest verify

GET http://localhost:3000/api/user/getVerify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNzYXNhYWEyZGFzZCIsInN1YiI6IjYxMTkwZTViZDZiMTlkNDI2Y2JhZWYyNiIsImlhdCI6MTYyOTAzMjk1NiwiZXhwIjoxNjI5MDY4OTU2fQ.kvnJ5_jhilxFzg0fHl9z7zb3dtF0cE6Cd5LLZwLkIsk