@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjFjMjI1NTdlMDM4NTc3NGNjODVhOTVlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NDE3Mzc1MDksImV4cCI6MTY0MTc3MzUwOX0.saBAKU1bPPRD_vIz2n-bftHDwT6hPYRW0kQdeWO5qiM
@set = 61db2daf67d6f719a06bac6c
@user = 61c22557e0385774cc85a95e
@adress = http://localhost:3001/api/sets

###Create Set
POST {{adress}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Jibba",
    "category": "classic"
}

### Get all sets
GET {{adress}}

### Get all sets by user
GET {{adress}}/user/{{user}}
#Authorization: Bearer {{token}}

### Get one set only active tasks
GET {{adress}}/{{set}}

### Update set metadata
PATCH {{adress}}/{{set}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "better name",
    "language": "en",
    "unicorn": "asd"
}

### Update Played
PATCH {{adress}}/{{set}}/played
Content-Type: application/json

### Soft Delete Set by Id
DELETE {{adress}}/{{set}}
Authorization: Bearer {{token}}

### Hard Delete Set by Id (require admin role)
DELETE {{adress}}/{{set}}?type=hard
Authorization: Bearer {{token}}

### Sample sets
POST {{adress}}/migrate
Content-Type: application/json
Authorization: Bearer {{token}}
