###Create Set
POST http://localhost:3000/api/set
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExZTQ3OWNmYTIxZjMxMDU4NTk4ZTYyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkzODE3NzIsImV4cCI6MTYyOTQxNzc3Mn0.HlPRET4yfafmnqNJCZNDnMyXMkwlqtqvHBmr_aBB2Oo

{
    "description": "Jeder hat schon mal Wahrheit oder Pflicht mit Freunden oder auf Partys gespielt. Hier kommt aber eine Sonderedition an Wahrheit-Fragen und Pflicht-Aufgaben für dich und deinen Crush, dein Girl- oder Boyfriend. Have Fun!",
    "taskList": [],
    "language": "de",
    "name": "super cool set"
}

### Get all sets
GET http://localhost:3000/api/set

### Get one set
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882

### Add/Update set task list
POST http://localhost:3000/api/set/611e66d7508d106504f645ab/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExZTQ3OWNmYTIxZjMxMDU4NTk4ZTYyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkzODI1MzgsImV4cCI6MTYyOTQxODUzOH0.C-DwlCpN33kUuFz8gqaZrnKVgN55JpsBw4oqiRJip8c

{
    "tasks": ["611c38b477070d296c8b972c"]
}

### Remove set task list
POST http://localhost:3000/api/set/611e66d7508d106504f645ab/remove
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkzODI3NTksImV4cCI6MTYyOTQxODc1OX0.-T2UMo_bkbaPb5bMVi6nJLUxARaBLGiLvMsZSF2T2gw

{
    "tasks": ["611c38b477070d296c8b972c"]
}

### Get Tasks in Set
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tasks1

### Get Tasks in Set2
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tasks

### Get top 10 Tasks in Set2
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tentasks

### Get Tasks in Set paginated
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tasks?page=0&limit=99999

### Get Set metadata
GET http://localhost:3000/api/set/6116ac912a8b143164f7f00b/meta
 
### Update set metadata
PATCH  http://localhost:3000/api/set/611e64951345e1678cac0422/meta
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkzODE4NzUsImV4cCI6MTYyOTQxNzg3NX0.qdNAA5iulacHcaSHyRItfgkWgIlhg0ZWkySl1ozyxno

{
    "name": "better name",
    "description": "gang gang"
}

### Upvote set via id
PATCH  http://localhost:3000/api/set/6117926bd45adc1f50dea882/upvote

### Downvote set via id
PATCH  http://localhost:3000/api/set/6117926bd45adc1f50dea882/downvote

### Soft Delete Set by Id
DELETE http://localhost:3000/api/set/611e53ad00c46627acbb5341
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjExZTQ3OWNmYTIxZjMxMDU4NTk4ZTYyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkzNzU2MTMsImV4cCI6MTYyOTQxMTYxM30.wsu_0AINoQMy1XNFPKY5qN4novKao7ThmmcA-p8KcaM

### Hard Delete Set by Id (require admin role)
DELETE http://localhost:3000/api/set/611e61328c72703e002f8f61?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkzNzc0OTgsImV4cCI6MTYyOTQxMzQ5OH0.LSjhHDDMFTIY_iLEaj-2FuJn2Ze2KmvpIcHAKoujFFA
