###Create Set
POST http://localhost:3000/api/set
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvcGVzaG90Iiwic3ViIjoiNjExOTYxYTgxZmEyOTkwMDE2MjM2YWFhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkyMzE4NTQsImV4cCI6MTYyOTI2Nzg1NH0.Bh_4A-rAWCxcTbOH7N3eUfvs-AtutlM3o50Jguy8xw8

{
    "creator": "6112ba6ea4a2b02db05c423a",
    "description": "Jeder hat schon mal Wahrheit oder Pflicht mit Freunden oder auf Partys gespielt. Hier kommt aber eine Sonderedition an Wahrheit-Fragen und Pflicht-Aufgaben für dich und deinen Crush, dein Girl- oder Boyfriend. Have Fun!",
    "taskList": [],
    "language": "de",
    "name": "Verliebte"
}

### Get all sets
GET http://localhost:3000/api/set

### Get one set
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882

### Update set task list
POST http://localhost:3000/api/set/611c1d4c1c20a66b5cdad7bf/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvcGVzaG90Iiwic3ViIjoiNjExOTYxYTgxZmEyOTkwMDE2MjM2YWFhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MjkyMzE4NTQsImV4cCI6MTYyOTI2Nzg1NH0.Bh_4A-rAWCxcTbOH7N3eUfvs-AtutlM3o50Jguy8xw8

{
"tasks": ["611c1e3b1c20a66b5cdad7c3", "611c1e611c20a66b5cdad7c5", "611c1e6c1c20a66b5cdad7c7", "611c1ec91c20a66b5cdad7c9", "611c1ee61c20a66b5cdad7cb", "611c1f161c20a66b5cdad7cd", "611c1f2d1c20a66b5cdad7cf"]
}

### Get Tasks in Set
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tasks1

### Get Tasks in Set2
GET http://localhost:3000/api/set/611c1d4c1c20a66b5cdad7bf/tasks

### Get top 10 Tasks in Set2
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tentasks

### Get Tasks in Set paginated
GET http://localhost:3000/api/set/6117926bd45adc1f50dea882/tasks?page=0&limit=99999

### Get Set metadata
GET http://localhost:3000/api/set/6116ac912a8b143164f7f00b/meta
 
### Update set metadata
PATCH  http://localhost:3000/api/set/6116ac912a8b143164f7f00b/meta
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

{
    "name": "better name",
    "description": "gang gang"
}

### Upvote set via id
PATCH  http://localhost:3000/api/set/6117926bd45adc1f50dea882/upvote

### Downvote set via id
PATCH  http://localhost:3000/api/set/6117926bd45adc1f50dea882/downvote

### Soft Delete Set by Id
DELETE http://localhost:3000/api/set/611520190a92523f38489c02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI

### Hard Delete Set by Id (require admin role)
DELETE http://localhost:3000/api/set/611659725b415a2d2072bc92?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOiI2MTE3ZDVhMTcwNDU1ODRmZjhkM2M2ODkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjkwNDg1NjQsImV4cCI6MTYyOTA4NDU2NH0.isQ63KUWVd_3-w1nqEM0ItcXWhjaTznz-g4VErlkkcI
