@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvIiwic3ViIjoiNjFjMjI1NTdlMDM4NTc3NGNjODVhOTVlIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjQyMTk5ODcyLCJleHAiOjE2NDIyMzU4NzJ9.6kr80KoeYGmaKlhNsZQpYXGqszOqX4o_4pPW2EL7RX8
@set = 61e200552cdd19f1e6e46c7c
@task = 618fb74b0fcab4672f471341
@adress = http://localhost:3001/api/sets/
###Create Task
POST {{adress}}{{set}}/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "truth",
    "currentPlayerGender": "@cm",
    "message" : "Boese Woerter weswegen der spas hier Inactiv ist!!"
}

### Update task
PUT {{adress}}{{set}}/task/{{task}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPlayerGender": "@ca",
    "type": "dare"
}

### Remove task
DELETE {{adress}}{{set}}/task/{{task}}
Authorization: Bearer {{token}}
