###Create Task
POST http://localhost:3000/api/set/617d1e370493d96c5466bcdd/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvcmVtIiwic3ViIjoiNjExYWRkYTEzMWZjNjU2OTk4NjFhMTE4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM1NjgxNzI2LCJleHAiOjE2MzU3MTc3MjZ9.GkcdiPT8KjUlFsoOmSBwQ1igBaPnqYLMYmM4jjhXRpg

{
    "type": "truth",
    "currentPlayerGender" : "@ca",
    "message" : "Boese Woerter weswegen der spas hier Inactiv ist!!"
}

