@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjFlODRlMzk2ZDhiYmZkOGM0YzdlMjRlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NDI2MTQ5MDUsImV4cCI6MTY0MjY1MDkwNX0.EovT_k2Hm0Z-6upgMsVgA0xFP2Uzl5FAkVcJGY-Hho4
@set = 61e84ebf1fb85c7f69808259
@task = 618fb74b0fcab4672f471341
@adress = http://localhost:3001/api/sets/
###Create Task
POST {{adress}}{{set}}/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "truth",
    "currentPlayerGender": "@ca",
    "message" : "Wie alt bist du?"
}

### Update task
PUT {{adress}}{{set}}/task/{{task}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPlayerGender": "@ca",
    "type": "dare"
}

### Remove task
DELETE {{adress}}{{set}}/task/{{task}}
Authorization: Bearer {{token}}
