@adress = http://localhost:3000/api/auth
### Register User
POST {{adress}}/register
Content-Type: application/json

{
    "username": "Hello",
    "email": "test@gmail.de",
    "password": "12345678"
}

### Login User
POST {{adress}}/login
Content-Type: application/json

{
    "email": "test@gmail.de",
    "password": "12345678"
}

### Google Auth
GET {{adress}}/google

### Facebook Auth
GET {{adress}}/facebook

### Discord Auth
GET {{adress}}/discord