@adress = http://localhost:3001/api/auth
### Register User
POST {{adress}}/register
Content-Type: application/json

{
    "username": "Heawdassdllo",
    "email": "teasdawasdawst@gmail.de",
    "password": "12345678"
}

### Login User
POST {{adress}}/login
Content-Type: application/json

{
    "email": "test@gmail.de",
    "password": "test213123123"
}

### Facebook Auth
GET {{adress}}/google

### Facebook Auth
GET {{adress}}/facebook

### Discord Auth
GET {{adress}}/discord