### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Joy",
    "email": "joy@gmail.com",
    "password": "12345678"
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Zoe",
    "password": "12345678"
}

### Google Auth
GET http://localhost:3000/api/auth/google
